name: link-check
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --verbose --no-progress --exclude-mail --max-redirects 5 --base .
            ./index.html ./app.html ./app-classic.html
            ./faq.html ./changelog.html ./tests.html
            ./partner.html ./danke.html
            ./bookmarklets.html ./impressum.html ./datenschutz.html
            ./sitemap.xml ./robots.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
